ci: add verify skip workflow

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,70 +1,70 @@
-# Copyright 2024 Defense Unicorns
-# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial
+# # Copyright 2024 Defense Unicorns
+# # SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial
 
-name: Test
+# name: Test
 
-on:
-  # This workflow is triggered on pull requests to the main branch.
-  pull_request:
-    # milestoned is added here so that a PR can be re-triggered if it is milestoned.
-    types: [milestoned, opened, reopened, synchronize]
-    paths-ignore:
-      - ".github/container-and-chart/**"
+# on:
+#   # This workflow is triggered on pull requests to the main branch.
+#   pull_request:
+#     # milestoned is added here so that a PR can be re-triggered if it is milestoned.
+#     types: [milestoned, opened, reopened, synchronize]
+#     paths-ignore:
+#       - ".github/container-and-chart/**"
 
-# Permissions for the GITHUB_TOKEN used by the workflow.
-permissions:
-  contents: read # Allows reading the content of the repository.
-  packages: read # Allows reading the content of the repository's packages.
-  pull-requests: read
-  id-token: write
+# # Permissions for the GITHUB_TOKEN used by the workflow.
+# permissions:
+#   contents: read # Allows reading the content of the repository.
+#   packages: read # Allows reading the content of the repository's packages.
+#   pull-requests: read
+#   id-token: write
 
-# Abort prior jobs in the same workflow / PR
-concurrency:
-  group: test-${{ github.ref }}
-  cancel-in-progress: true
+# # Abort prior jobs in the same workflow / PR
+# concurrency:
+#   group: test-${{ github.ref }}
+#   cancel-in-progress: true
 
-jobs:
-  check-flavor:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+# jobs:
+#   check-flavor:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
 
-      - name: test-flavor
-        uses: defenseunicorns/uds-common/.github/actions/test-flavor@ba03e5bec6704a54466a94a3fdee9741b755630b # v1.24.11
-        id: test-flavor
-    outputs:
-      upgrade-flavors: ${{ steps.test-flavor.outputs.upgrade-flavors }}
+#       - name: test-flavor
+#         uses: defenseunicorns/uds-common/.github/actions/test-flavor@ba03e5bec6704a54466a94a3fdee9741b755630b # v1.24.11
+#         id: test-flavor
+#     outputs:
+#       upgrade-flavors: ${{ steps.test-flavor.outputs.upgrade-flavors }}
 
-  validate:
-    needs: check-flavor
-    strategy:
-      fail-fast: false
-      matrix:
-        type: [install, upgrade]
-        flavor: [upstream, unicorn]
-    uses: defenseunicorns/uds-common/.github/workflows/callable-test.yaml@ba03e5bec6704a54466a94a3fdee9741b755630b # v1.24.11
-    with:
-      timeout: 30
-      options: --set BASE_REPO="ghcr.io/uds-packages"
-      runsOn: appstore-4-core-amd64
-      upgrade-flavors: ${{ needs.check-flavor.outputs.upgrade-flavors }}
-      flavor: ${{ matrix.flavor }}
-      type: ${{ matrix.type }}
-    secrets: inherit # Inherits all secrets from the parent workflow.
+#   validate:
+#     needs: check-flavor
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         type: [install, upgrade]
+#         flavor: [upstream, unicorn]
+#     uses: defenseunicorns/uds-common/.github/workflows/callable-test.yaml@ba03e5bec6704a54466a94a3fdee9741b755630b # v1.24.11
+#     with:
+#       timeout: 30
+#       options: --set BASE_REPO="ghcr.io/uds-packages"
+#       runsOn: appstore-4-core-amd64
+#       upgrade-flavors: ${{ needs.check-flavor.outputs.upgrade-flavors }}
+#       flavor: ${{ matrix.flavor }}
+#       type: ${{ matrix.type }}
+#     secrets: inherit # Inherits all secrets from the parent workflow.
 
-  verify-test:
-    runs-on: ubuntu-latest
-    needs: validate
-    if: always()
-    steps:
-      - name: Check validate result
-        run: |
-          echo "validate result: ${{ needs.validate.result }}"
+#   verify-test:
+#     runs-on: ubuntu-latest
+#     needs: validate
+#     if: always()
+#     steps:
+#       - name: Check validate result
+#         run: |
+#           echo "validate result: ${{ needs.validate.result }}"
 
-          if [ "${{ needs.validate.result }}" != "success" ]; then
-            echo "One or more tests failed."
-            exit 1
-          fi
+#           if [ "${{ needs.validate.result }}" != "success" ]; then
+#             echo "One or more tests failed."
+#             exit 1
+#           fi
 
-          echo "All tests passed successfully!"
+#           echo "All tests passed successfully!"
